/**
 * Curated India city → state map.
 *
 * Used to auto-fill the State field once the user picks a City in the
 * checkout form. Covers the top ~600 cities by population so that the
 * common case "just works"; the form falls back to manual state entry
 * for anything not in this list (rural users are never blocked).
 *
 * If a city legitimately exists in more than one state (e.g. Aurangabad
 * in Maharashtra and Bihar), we map it to the larger / more
 * well-known one. The user can always override by typing the state
 * manually after clearing the city field.
 *
 * Keys are stored title-cased; lookups are case-insensitive via
 * `lookupStateForCity()`.
 */

export const INDIAN_STATES: readonly string[] = [
  // 28 States
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  // 8 Union Territories
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

/** Major cities mapped to their state / UT. */
export const CITY_STATE_MAP: Readonly<Record<string, string>> = {
  // Andhra Pradesh
  Visakhapatnam: "Andhra Pradesh",
  Vijayawada: "Andhra Pradesh",
  Guntur: "Andhra Pradesh",
  Nellore: "Andhra Pradesh",
  Kurnool: "Andhra Pradesh",
  Rajahmundry: "Andhra Pradesh",
  Tirupati: "Andhra Pradesh",
  Kakinada: "Andhra Pradesh",
  Anantapur: "Andhra Pradesh",
  Kadapa: "Andhra Pradesh",
  Eluru: "Andhra Pradesh",
  Ongole: "Andhra Pradesh",
  Chittoor: "Andhra Pradesh",
  Machilipatnam: "Andhra Pradesh",
  Srikakulam: "Andhra Pradesh",
  Vizianagaram: "Andhra Pradesh",
  Tenali: "Andhra Pradesh",
  Proddatur: "Andhra Pradesh",
  Hindupur: "Andhra Pradesh",
  Bhimavaram: "Andhra Pradesh",

  // Arunachal Pradesh
  Itanagar: "Arunachal Pradesh",
  Naharlagun: "Arunachal Pradesh",
  Pasighat: "Arunachal Pradesh",
  Tezu: "Arunachal Pradesh",
  Ziro: "Arunachal Pradesh",

  // Assam
  Guwahati: "Assam",
  Silchar: "Assam",
  Dibrugarh: "Assam",
  Jorhat: "Assam",
  Nagaon: "Assam",
  Tinsukia: "Assam",
  Tezpur: "Assam",
  Bongaigaon: "Assam",
  Karimganj: "Assam",
  Dhubri: "Assam",
  Diphu: "Assam",
  Goalpara: "Assam",
  Sivasagar: "Assam",
  Barpeta: "Assam",
  "North Lakhimpur": "Assam",

  // Bihar
  Patna: "Bihar",
  Gaya: "Bihar",
  Bhagalpur: "Bihar",
  Muzaffarpur: "Bihar",
  Purnia: "Bihar",
  Darbhanga: "Bihar",
  "Bihar Sharif": "Bihar",
  Arrah: "Bihar",
  Begusarai: "Bihar",
  Katihar: "Bihar",
  Munger: "Bihar",
  Chhapra: "Bihar",
  Saharsa: "Bihar",
  Hajipur: "Bihar",
  Sasaram: "Bihar",
  Dehri: "Bihar",
  Siwan: "Bihar",
  Motihari: "Bihar",
  Nawada: "Bihar",
  Bagaha: "Bihar",
  Buxar: "Bihar",
  Kishanganj: "Bihar",
  Jamalpur: "Bihar",
  Jehanabad: "Bihar",

  // Chhattisgarh
  Raipur: "Chhattisgarh",
  Bhilai: "Chhattisgarh",
  Bilaspur: "Chhattisgarh",
  Korba: "Chhattisgarh",
  Durg: "Chhattisgarh",
  Rajnandgaon: "Chhattisgarh",
  Jagdalpur: "Chhattisgarh",
  Raigarh: "Chhattisgarh",
  Ambikapur: "Chhattisgarh",
  Mahasamund: "Chhattisgarh",
  Dhamtari: "Chhattisgarh",
  Chirmiri: "Chhattisgarh",

  // Goa
  Panaji: "Goa",
  Margao: "Goa",
  "Vasco da Gama": "Goa",
  Mapusa: "Goa",
  Ponda: "Goa",
  Bicholim: "Goa",
  Curchorem: "Goa",
  Cuncolim: "Goa",
  Sanquelim: "Goa",
  Canacona: "Goa",

  // Gujarat
  Ahmedabad: "Gujarat",
  Surat: "Gujarat",
  Vadodara: "Gujarat",
  Rajkot: "Gujarat",
  Bhavnagar: "Gujarat",
  Jamnagar: "Gujarat",
  Gandhinagar: "Gujarat",
  Junagadh: "Gujarat",
  Anand: "Gujarat",
  Nadiad: "Gujarat",
  Morbi: "Gujarat",
  Mehsana: "Gujarat",
  Bharuch: "Gujarat",
  Surendranagar: "Gujarat",
  Navsari: "Gujarat",
  Vapi: "Gujarat",
  Veraval: "Gujarat",
  Porbandar: "Gujarat",
  Godhra: "Gujarat",
  Dwarka: "Gujarat",
  Palanpur: "Gujarat",
  Valsad: "Gujarat",
  Patan: "Gujarat",
  Botad: "Gujarat",
  Amreli: "Gujarat",
  Deesa: "Gujarat",
  Jetpur: "Gujarat",
  Kalol: "Gujarat",
  Dahod: "Gujarat",
  Gondal: "Gujarat",

  // Haryana
  Faridabad: "Haryana",
  Gurugram: "Haryana",
  Gurgaon: "Haryana",
  Panipat: "Haryana",
  Ambala: "Haryana",
  Yamunanagar: "Haryana",
  Rohtak: "Haryana",
  Hisar: "Haryana",
  Karnal: "Haryana",
  Sonipat: "Haryana",
  Panchkula: "Haryana",
  Bhiwani: "Haryana",
  Sirsa: "Haryana",
  Bahadurgarh: "Haryana",
  Jind: "Haryana",
  Thanesar: "Haryana",
  Kaithal: "Haryana",
  Rewari: "Haryana",
  Palwal: "Haryana",
  Kurukshetra: "Haryana",
  Fatehabad: "Haryana",

  // Himachal Pradesh
  Shimla: "Himachal Pradesh",
  Mandi: "Himachal Pradesh",
  Solan: "Himachal Pradesh",
  Dharamshala: "Himachal Pradesh",
  Kullu: "Himachal Pradesh",
  Manali: "Himachal Pradesh",
  Hamirpur: "Himachal Pradesh",
  Una: "Himachal Pradesh",
  "Bilaspur HP": "Himachal Pradesh",
  Chamba: "Himachal Pradesh",
  Palampur: "Himachal Pradesh",
  Kangra: "Himachal Pradesh",
  Sundernagar: "Himachal Pradesh",
  Nahan: "Himachal Pradesh",

  // Jharkhand
  Ranchi: "Jharkhand",
  Jamshedpur: "Jharkhand",
  Dhanbad: "Jharkhand",
  Bokaro: "Jharkhand",
  Deoghar: "Jharkhand",
  Hazaribagh: "Jharkhand",
  Giridih: "Jharkhand",
  Ramgarh: "Jharkhand",
  Phusro: "Jharkhand",
  Medininagar: "Jharkhand",
  Chaibasa: "Jharkhand",
  Dumka: "Jharkhand",
  Chirkunda: "Jharkhand",

  // Karnataka
  Bengaluru: "Karnataka",
  Bangalore: "Karnataka",
  Mysuru: "Karnataka",
  Mysore: "Karnataka",
  Mangaluru: "Karnataka",
  Mangalore: "Karnataka",
  Hubballi: "Karnataka",
  Hubli: "Karnataka",
  Belagavi: "Karnataka",
  Belgaum: "Karnataka",
  Kalaburagi: "Karnataka",
  Gulbarga: "Karnataka",
  Davangere: "Karnataka",
  Ballari: "Karnataka",
  Bellary: "Karnataka",
  Vijayapura: "Karnataka",
  Bijapur: "Karnataka",
  Shivamogga: "Karnataka",
  Shimoga: "Karnataka",
  Tumakuru: "Karnataka",
  Tumkur: "Karnataka",
  Raichur: "Karnataka",
  Bidar: "Karnataka",
  Hospet: "Karnataka",
  Hassan: "Karnataka",
  Gadag: "Karnataka",
  Udupi: "Karnataka",
  Chitradurga: "Karnataka",
  Kolar: "Karnataka",
  Mandya: "Karnataka",
  Chikkamagaluru: "Karnataka",
  Karwar: "Karnataka",

  // Kerala
  Thiruvananthapuram: "Kerala",
  Trivandrum: "Kerala",
  Kochi: "Kerala",
  Cochin: "Kerala",
  Ernakulam: "Kerala",
  Kozhikode: "Kerala",
  Calicut: "Kerala",
  Thrissur: "Kerala",
  Trichur: "Kerala",
  Kollam: "Kerala",
  Quilon: "Kerala",
  Palakkad: "Kerala",
  Alappuzha: "Kerala",
  Alleppey: "Kerala",
  Kannur: "Kerala",
  Cannanore: "Kerala",
  Kottayam: "Kerala",
  Malappuram: "Kerala",
  Kasaragod: "Kerala",
  Pathanamthitta: "Kerala",
  Idukki: "Kerala",
  Wayanad: "Kerala",
  Guruvayur: "Kerala",
  Munnar: "Kerala",
  Varkala: "Kerala",

  // Madhya Pradesh
  Indore: "Madhya Pradesh",
  Bhopal: "Madhya Pradesh",
  Jabalpur: "Madhya Pradesh",
  Gwalior: "Madhya Pradesh",
  Ujjain: "Madhya Pradesh",
  Sagar: "Madhya Pradesh",
  Dewas: "Madhya Pradesh",
  Satna: "Madhya Pradesh",
  Ratlam: "Madhya Pradesh",
  Rewa: "Madhya Pradesh",
  Murwara: "Madhya Pradesh",
  Singrauli: "Madhya Pradesh",
  Burhanpur: "Madhya Pradesh",
  Khandwa: "Madhya Pradesh",
  Bhind: "Madhya Pradesh",
  Chhindwara: "Madhya Pradesh",
  Guna: "Madhya Pradesh",
  Shivpuri: "Madhya Pradesh",
  Vidisha: "Madhya Pradesh",
  Chhatarpur: "Madhya Pradesh",
  Damoh: "Madhya Pradesh",
  Mandsaur: "Madhya Pradesh",
  Khargone: "Madhya Pradesh",
  Neemuch: "Madhya Pradesh",
  Pithampur: "Madhya Pradesh",
  Hoshangabad: "Madhya Pradesh",
  Itarsi: "Madhya Pradesh",
  Sehore: "Madhya Pradesh",
  Morena: "Madhya Pradesh",
  Betul: "Madhya Pradesh",
  Datia: "Madhya Pradesh",
  Nagda: "Madhya Pradesh",

  // Maharashtra
  Mumbai: "Maharashtra",
  Pune: "Maharashtra",
  Nagpur: "Maharashtra",
  Nashik: "Maharashtra",
  Aurangabad: "Maharashtra",
  Solapur: "Maharashtra",
  Thane: "Maharashtra",
  "Navi Mumbai": "Maharashtra",
  Amravati: "Maharashtra",
  Kolhapur: "Maharashtra",
  Sangli: "Maharashtra",
  Akola: "Maharashtra",
  Latur: "Maharashtra",
  Dhule: "Maharashtra",
  Ahmednagar: "Maharashtra",
  Chandrapur: "Maharashtra",
  Jalgaon: "Maharashtra",
  Nanded: "Maharashtra",
  Parbhani: "Maharashtra",
  Ichalkaranji: "Maharashtra",
  Jalna: "Maharashtra",
  Bhiwandi: "Maharashtra",
  Wardha: "Maharashtra",
  Yavatmal: "Maharashtra",
  Satara: "Maharashtra",
  Beed: "Maharashtra",
  Osmanabad: "Maharashtra",
  Hingoli: "Maharashtra",
  Buldhana: "Maharashtra",
  Washim: "Maharashtra",
  Ratnagiri: "Maharashtra",
  Sindhudurg: "Maharashtra",
  Raigad: "Maharashtra",
  Panvel: "Maharashtra",
  Vasai: "Maharashtra",
  Virar: "Maharashtra",
  Kalyan: "Maharashtra",
  Dombivli: "Maharashtra",
  Ulhasnagar: "Maharashtra",
  "Mira Bhayandar": "Maharashtra",
  Shirdi: "Maharashtra",

  // Manipur
  Imphal: "Manipur",
  Thoubal: "Manipur",
  Bishnupur: "Manipur",
  Churachandpur: "Manipur",
  Ukhrul: "Manipur",
  Senapati: "Manipur",
  Kakching: "Manipur",

  // Meghalaya
  Shillong: "Meghalaya",
  Tura: "Meghalaya",
  Jowai: "Meghalaya",
  Nongstoin: "Meghalaya",
  Williamnagar: "Meghalaya",

  // Mizoram
  Aizawl: "Mizoram",
  Lunglei: "Mizoram",
  Champhai: "Mizoram",
  Serchhip: "Mizoram",
  Kolasib: "Mizoram",

  // Nagaland
  Kohima: "Nagaland",
  Dimapur: "Nagaland",
  Mokokchung: "Nagaland",
  Tuensang: "Nagaland",
  Wokha: "Nagaland",
  Zunheboto: "Nagaland",
  Mon: "Nagaland",

  // Odisha
  Bhubaneswar: "Odisha",
  Cuttack: "Odisha",
  Rourkela: "Odisha",
  Berhampur: "Odisha",
  Sambalpur: "Odisha",
  Puri: "Odisha",
  Balasore: "Odisha",
  Bhadrak: "Odisha",
  Baripada: "Odisha",
  Jharsuguda: "Odisha",
  Jeypore: "Odisha",
  Brahmapur: "Odisha",
  Bargarh: "Odisha",
  Rayagada: "Odisha",
  Koraput: "Odisha",
  Angul: "Odisha",
  Dhenkanal: "Odisha",
  Kendrapara: "Odisha",
  Paradip: "Odisha",
  Jajpur: "Odisha",

  // Punjab
  Ludhiana: "Punjab",
  Amritsar: "Punjab",
  Jalandhar: "Punjab",
  Patiala: "Punjab",
  Bathinda: "Punjab",
  Hoshiarpur: "Punjab",
  Mohali: "Punjab",
  Pathankot: "Punjab",
  Moga: "Punjab",
  Abohar: "Punjab",
  Malerkotla: "Punjab",
  Khanna: "Punjab",
  Phagwara: "Punjab",
  Muktsar: "Punjab",
  Barnala: "Punjab",
  Rajpura: "Punjab",
  Firozpur: "Punjab",
  Kapurthala: "Punjab",
  Faridkot: "Punjab",
  Sangrur: "Punjab",
  Mansa: "Punjab",
  Gurdaspur: "Punjab",

  // Rajasthan
  Jaipur: "Rajasthan",
  Jodhpur: "Rajasthan",
  Udaipur: "Rajasthan",
  Kota: "Rajasthan",
  Ajmer: "Rajasthan",
  Bikaner: "Rajasthan",
  Alwar: "Rajasthan",
  Bhilwara: "Rajasthan",
  Sikar: "Rajasthan",
  Pali: "Rajasthan",
  Tonk: "Rajasthan",
  "Sri Ganganagar": "Rajasthan",
  Kishangarh: "Rajasthan",
  Beawar: "Rajasthan",
  Hanumangarh: "Rajasthan",
  Dhaulpur: "Rajasthan",
  Gangapur: "Rajasthan",
  "Sawai Madhopur": "Rajasthan",
  Churu: "Rajasthan",
  Jhunjhunu: "Rajasthan",
  Bharatpur: "Rajasthan",
  Banswara: "Rajasthan",
  Pushkar: "Rajasthan",
  "Mount Abu": "Rajasthan",
  Nathdwara: "Rajasthan",
  Chittorgarh: "Rajasthan",
  Jaisalmer: "Rajasthan",
  Barmer: "Rajasthan",
  Nagaur: "Rajasthan",
  Dungarpur: "Rajasthan",
  Sirohi: "Rajasthan",
  Jhalawar: "Rajasthan",
  Bundi: "Rajasthan",
  Baran: "Rajasthan",
  Karauli: "Rajasthan",

  // Sikkim
  Gangtok: "Sikkim",
  Namchi: "Sikkim",
  Gyalshing: "Sikkim",
  Mangan: "Sikkim",
  Pelling: "Sikkim",
  Rangpo: "Sikkim",

  // Tamil Nadu
  Chennai: "Tamil Nadu",
  Coimbatore: "Tamil Nadu",
  Madurai: "Tamil Nadu",
  Tiruchirappalli: "Tamil Nadu",
  Trichy: "Tamil Nadu",
  Salem: "Tamil Nadu",
  Tirunelveli: "Tamil Nadu",
  Tiruppur: "Tamil Nadu",
  Vellore: "Tamil Nadu",
  Erode: "Tamil Nadu",
  Thoothukudi: "Tamil Nadu",
  Tuticorin: "Tamil Nadu",
  Dindigul: "Tamil Nadu",
  Thanjavur: "Tamil Nadu",
  Ranipet: "Tamil Nadu",
  Sivakasi: "Tamil Nadu",
  Karur: "Tamil Nadu",
  Udhagamandalam: "Tamil Nadu",
  Ooty: "Tamil Nadu",
  Hosur: "Tamil Nadu",
  Nagercoil: "Tamil Nadu",
  Kanchipuram: "Tamil Nadu",
  Kumbakonam: "Tamil Nadu",
  Tiruvannamalai: "Tamil Nadu",
  Pollachi: "Tamil Nadu",
  Rajapalayam: "Tamil Nadu",
  Gudiyatham: "Tamil Nadu",
  Pudukkottai: "Tamil Nadu",
  Vaniyambadi: "Tamil Nadu",
  Ambur: "Tamil Nadu",
  Nagapattinam: "Tamil Nadu",
  Cuddalore: "Tamil Nadu",
  Kanyakumari: "Tamil Nadu",
  Rameswaram: "Tamil Nadu",
  Chidambaram: "Tamil Nadu",

  // Telangana
  Hyderabad: "Telangana",
  Warangal: "Telangana",
  Nizamabad: "Telangana",
  Khammam: "Telangana",
  Karimnagar: "Telangana",
  Ramagundam: "Telangana",
  Mahabubnagar: "Telangana",
  Nalgonda: "Telangana",
  Adilabad: "Telangana",
  Suryapet: "Telangana",
  Miryalaguda: "Telangana",
  Siddipet: "Telangana",
  Jagtial: "Telangana",
  Mancherial: "Telangana",
  Bhongir: "Telangana",
  Medak: "Telangana",
  Vikarabad: "Telangana",
  Sangareddy: "Telangana",
  Secunderabad: "Telangana",

  // Tripura
  Agartala: "Tripura",
  "Udaipur Tripura": "Tripura",
  Dharmanagar: "Tripura",
  Kailashahar: "Tripura",
  Belonia: "Tripura",
  Ambassa: "Tripura",

  // Uttar Pradesh
  Lucknow: "Uttar Pradesh",
  Kanpur: "Uttar Pradesh",
  Ghaziabad: "Uttar Pradesh",
  Agra: "Uttar Pradesh",
  Varanasi: "Uttar Pradesh",
  Meerut: "Uttar Pradesh",
  Prayagraj: "Uttar Pradesh",
  Allahabad: "Uttar Pradesh",
  Bareilly: "Uttar Pradesh",
  Aligarh: "Uttar Pradesh",
  Moradabad: "Uttar Pradesh",
  Saharanpur: "Uttar Pradesh",
  Gorakhpur: "Uttar Pradesh",
  Noida: "Uttar Pradesh",
  "Greater Noida": "Uttar Pradesh",
  Firozabad: "Uttar Pradesh",
  Jhansi: "Uttar Pradesh",
  Muzaffarnagar: "Uttar Pradesh",
  Mathura: "Uttar Pradesh",
  Vrindavan: "Uttar Pradesh",
  Ayodhya: "Uttar Pradesh",
  Rampur: "Uttar Pradesh",
  Shahjahanpur: "Uttar Pradesh",
  Farrukhabad: "Uttar Pradesh",
  Mau: "Uttar Pradesh",
  Hapur: "Uttar Pradesh",
  Etawah: "Uttar Pradesh",
  Mirzapur: "Uttar Pradesh",
  Bulandshahr: "Uttar Pradesh",
  Sambhal: "Uttar Pradesh",
  Amroha: "Uttar Pradesh",
  Hardoi: "Uttar Pradesh",
  Fatehpur: "Uttar Pradesh",
  Raebareli: "Uttar Pradesh",
  Orai: "Uttar Pradesh",
  Sitapur: "Uttar Pradesh",
  Bahraich: "Uttar Pradesh",
  Modinagar: "Uttar Pradesh",
  Unnao: "Uttar Pradesh",
  Jaunpur: "Uttar Pradesh",
  Lakhimpur: "Uttar Pradesh",
  Hathras: "Uttar Pradesh",
  Banda: "Uttar Pradesh",
  Pilibhit: "Uttar Pradesh",
  Barabanki: "Uttar Pradesh",
  Khurja: "Uttar Pradesh",
  Gonda: "Uttar Pradesh",
  Mainpuri: "Uttar Pradesh",
  Lalitpur: "Uttar Pradesh",
  Etah: "Uttar Pradesh",
  Deoria: "Uttar Pradesh",
  Ujhani: "Uttar Pradesh",
  Ghazipur: "Uttar Pradesh",
  Sultanpur: "Uttar Pradesh",
  Azamgarh: "Uttar Pradesh",
  Bijnor: "Uttar Pradesh",
  Sahaswan: "Uttar Pradesh",
  Basti: "Uttar Pradesh",
  Chandausi: "Uttar Pradesh",
  Akbarpur: "Uttar Pradesh",

  // Uttarakhand
  Dehradun: "Uttarakhand",
  Haridwar: "Uttarakhand",
  Roorkee: "Uttarakhand",
  Haldwani: "Uttarakhand",
  Rudrapur: "Uttarakhand",
  Kashipur: "Uttarakhand",
  Rishikesh: "Uttarakhand",
  Nainital: "Uttarakhand",
  Mussoorie: "Uttarakhand",
  Almora: "Uttarakhand",
  Pithoragarh: "Uttarakhand",
  Pauri: "Uttarakhand",
  Chamoli: "Uttarakhand",
  Tehri: "Uttarakhand",
  Bageshwar: "Uttarakhand",
  Champawat: "Uttarakhand",

  // West Bengal
  Kolkata: "West Bengal",
  Howrah: "West Bengal",
  Asansol: "West Bengal",
  Siliguri: "West Bengal",
  Durgapur: "West Bengal",
  Bardhaman: "West Bengal",
  Malda: "West Bengal",
  Baharampur: "West Bengal",
  Habra: "West Bengal",
  Kharagpur: "West Bengal",
  Shantipur: "West Bengal",
  Dankuni: "West Bengal",
  Dhulian: "West Bengal",
  Ranaghat: "West Bengal",
  Haldia: "West Bengal",
  Raiganj: "West Bengal",
  Krishnanagar: "West Bengal",
  Nabadwip: "West Bengal",
  Medinipur: "West Bengal",
  Jalpaiguri: "West Bengal",
  Balurghat: "West Bengal",
  Basirhat: "West Bengal",
  Bankura: "West Bengal",
  Chakdaha: "West Bengal",
  Darjeeling: "West Bengal",
  Alipurduar: "West Bengal",
  Purulia: "West Bengal",
  Jangipur: "West Bengal",
  Bolpur: "West Bengal",
  Bangaon: "West Bengal",
  "Cooch Behar": "West Bengal",

  // Andaman and Nicobar Islands
  "Port Blair": "Andaman and Nicobar Islands",

  // Chandigarh
  Chandigarh: "Chandigarh",

  // Dadra and Nagar Haveli and Daman and Diu
  Silvassa: "Dadra and Nagar Haveli and Daman and Diu",
  Daman: "Dadra and Nagar Haveli and Daman and Diu",
  Diu: "Dadra and Nagar Haveli and Daman and Diu",

  // Delhi
  Delhi: "Delhi",
  "New Delhi": "Delhi",

  // Jammu and Kashmir
  Srinagar: "Jammu and Kashmir",
  Jammu: "Jammu and Kashmir",
  Anantnag: "Jammu and Kashmir",
  Baramulla: "Jammu and Kashmir",
  Sopore: "Jammu and Kashmir",
  Kathua: "Jammu and Kashmir",
  Udhampur: "Jammu and Kashmir",
  Punch: "Jammu and Kashmir",
  Rajouri: "Jammu and Kashmir",
  Kupwara: "Jammu and Kashmir",
  Pulwama: "Jammu and Kashmir",
  Budgam: "Jammu and Kashmir",

  // Ladakh
  Leh: "Ladakh",
  Kargil: "Ladakh",

  // Lakshadweep
  Kavaratti: "Lakshadweep",

  // Puducherry
  Puducherry: "Puducherry",
  Pondicherry: "Puducherry",
  Karaikal: "Puducherry",
  Yanam: "Puducherry",
  Mahe: "Puducherry",
};

/** All city names (for autocomplete suggestions). */
export const CITY_NAMES: readonly string[] = Object.keys(CITY_STATE_MAP).sort();

// Case-insensitive lookup index.
const LOWER_INDEX: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [city, state] of Object.entries(CITY_STATE_MAP)) {
    out[city.toLowerCase()] = state;
  }
  return out;
})();

/**
 * Look up the state for a given city name. Case-insensitive; returns
 * `null` if the city is not in our curated list (the caller should then
 * leave the state field enabled for manual entry).
 */
export function lookupStateForCity(city: string): string | null {
  if (!city) return null;
  return LOWER_INDEX[city.trim().toLowerCase()] ?? null;
}

// Reverse index: state -> sorted list of cities in that state.
const CITIES_BY_STATE: Readonly<Record<string, readonly string[]>> = (() => {
  const out: Record<string, string[]> = {};
  for (const [city, state] of Object.entries(CITY_STATE_MAP)) {
    (out[state] ??= []).push(city);
  }
  for (const k of Object.keys(out)) out[k].sort();
  return out;
})();

/**
 * Return the sorted list of curated cities for the given state. Empty
 * array if the state is unknown or has no curated entries (the caller
 * can then fall back to a free-text city input).
 */
export function lookupCitiesForState(state: string): readonly string[] {
  if (!state) return [];
  return CITIES_BY_STATE[state] ?? [];
}

/**
 * Default (head-post-office / central) pincode per city. Used to pre-fill
 * the checkout pincode field once a city is picked; the user can always
 * override. A city missing from this map simply leaves the pincode blank
 * (no fake data — the user types it themselves).
 *
 * Source: well-known HPO / district HQ pincodes from India Post.
 */
export const CITY_PINCODE_MAP: Readonly<Record<string, string>> = {
  // Andhra Pradesh
  Visakhapatnam: "530001",
  Vijayawada: "520001",
  Guntur: "522001",
  Nellore: "524001",
  Kurnool: "518001",
  Rajahmundry: "533101",
  Tirupati: "517501",
  Kakinada: "533001",
  Anantapur: "515001",
  Kadapa: "516001",
  // Arunachal Pradesh
  Itanagar: "791111",
  // Assam
  Guwahati: "781001",
  Silchar: "788001",
  Dibrugarh: "786001",
  Jorhat: "785001",
  Nagaon: "782001",
  Tezpur: "784001",
  // Bihar
  Patna: "800001",
  Gaya: "823001",
  Bhagalpur: "812001",
  Muzaffarpur: "842001",
  Purnia: "854301",
  Darbhanga: "846004",
  Begusarai: "851101",
  // Chhattisgarh
  Raipur: "492001",
  Bhilai: "490001",
  Bilaspur: "495001",
  Korba: "495677",
  Durg: "491001",
  // Goa
  Panaji: "403001",
  Margao: "403601",
  "Vasco da Gama": "403802",
  Mapusa: "403507",
  Ponda: "403401",
  // Gujarat
  Ahmedabad: "380001",
  Surat: "395003",
  Vadodara: "390001",
  Rajkot: "360001",
  Bhavnagar: "364001",
  Jamnagar: "361001",
  Gandhinagar: "382010",
  Junagadh: "362001",
  Anand: "388001",
  Nadiad: "387001",
  Bharuch: "392001",
  Navsari: "396445",
  Dwarka: "361335",
  Porbandar: "360575",
  // Haryana
  Faridabad: "121001",
  Gurugram: "122001",
  Gurgaon: "122001",
  Panipat: "132103",
  Ambala: "134003",
  Yamunanagar: "135001",
  Rohtak: "124001",
  Hisar: "125001",
  Karnal: "132001",
  Sonipat: "131001",
  Panchkula: "134109",
  Rewari: "123401",
  Kurukshetra: "136118",
  // Himachal Pradesh
  Shimla: "171001",
  Mandi: "175001",
  Solan: "173212",
  Dharamshala: "176215",
  Kullu: "175101",
  Manali: "175131",
  Hamirpur: "177001",
  Una: "174303",
  Palampur: "176061",
  // Jharkhand
  Ranchi: "834001",
  Jamshedpur: "831001",
  Dhanbad: "826001",
  Bokaro: "827001",
  Deoghar: "814112",
  Hazaribagh: "825301",
  // Karnataka
  Bengaluru: "560001",
  Bangalore: "560001",
  Mysuru: "570001",
  Mysore: "570001",
  Mangaluru: "575001",
  Mangalore: "575001",
  Hubballi: "580020",
  Hubli: "580020",
  Belagavi: "590001",
  Belgaum: "590001",
  Kalaburagi: "585101",
  Gulbarga: "585101",
  Davangere: "577001",
  Ballari: "583101",
  Bellary: "583101",
  Vijayapura: "586101",
  Bijapur: "586101",
  Shivamogga: "577201",
  Shimoga: "577201",
  Tumakuru: "572101",
  Tumkur: "572101",
  Udupi: "576101",
  Hassan: "573201",
  // Kerala
  Thiruvananthapuram: "695001",
  Trivandrum: "695001",
  Kochi: "682001",
  Cochin: "682001",
  Ernakulam: "682011",
  Kozhikode: "673001",
  Calicut: "673001",
  Thrissur: "680001",
  Trichur: "680001",
  Kollam: "691001",
  Quilon: "691001",
  Palakkad: "678001",
  Alappuzha: "688001",
  Alleppey: "688001",
  Kannur: "670001",
  Cannanore: "670001",
  Kottayam: "686001",
  Malappuram: "676505",
  Kasaragod: "671121",
  Guruvayur: "680101",
  Munnar: "685612",
  Varkala: "695141",
  // Madhya Pradesh
  Indore: "452001",
  Bhopal: "462001",
  Jabalpur: "482001",
  Gwalior: "474001",
  Ujjain: "456001",
  Sagar: "470001",
  Dewas: "455001",
  Satna: "485001",
  Ratlam: "457001",
  Rewa: "486001",
  // Maharashtra
  Mumbai: "400001",
  Pune: "411001",
  Nagpur: "440001",
  Nashik: "422001",
  Aurangabad: "431001",
  Solapur: "413001",
  Thane: "400601",
  "Navi Mumbai": "400703",
  Amravati: "444601",
  Kolhapur: "416001",
  Sangli: "416416",
  Akola: "444001",
  Latur: "413512",
  Dhule: "424001",
  Ahmednagar: "414001",
  Chandrapur: "442401",
  Jalgaon: "425001",
  Nanded: "431601",
  Satara: "415001",
  Ratnagiri: "415612",
  Panvel: "410206",
  Vasai: "401201",
  Virar: "401303",
  Kalyan: "421301",
  Dombivli: "421201",
  Shirdi: "423109",
  // Manipur
  Imphal: "795001",
  // Meghalaya
  Shillong: "793001",
  Tura: "794001",
  // Mizoram
  Aizawl: "796001",
  // Nagaland
  Kohima: "797001",
  Dimapur: "797112",
  // Odisha
  Bhubaneswar: "751001",
  Cuttack: "753001",
  Rourkela: "769001",
  Berhampur: "760001",
  Sambalpur: "768001",
  Puri: "752001",
  Balasore: "756001",
  // Punjab
  Ludhiana: "141001",
  Amritsar: "143001",
  Jalandhar: "144001",
  Patiala: "147001",
  Bathinda: "151001",
  Hoshiarpur: "146001",
  Mohali: "160055",
  Pathankot: "145001",
  Moga: "142001",
  Phagwara: "144401",
  Firozpur: "152002",
  // Rajasthan
  Jaipur: "302001",
  Jodhpur: "342001",
  Udaipur: "313001",
  Kota: "324001",
  Ajmer: "305001",
  Bikaner: "334001",
  Alwar: "301001",
  Bhilwara: "311001",
  Sikar: "332001",
  Pali: "306401",
  Tonk: "304001",
  "Sri Ganganagar": "335001",
  Bharatpur: "321001",
  Pushkar: "305022",
  "Mount Abu": "307501",
  Nathdwara: "313301",
  Chittorgarh: "312001",
  Jaisalmer: "345001",
  Barmer: "344001",
  Banswara: "327001",
  // Sikkim
  Gangtok: "737101",
  // Tamil Nadu
  Chennai: "600001",
  Coimbatore: "641001",
  Madurai: "625001",
  Tiruchirappalli: "620001",
  Trichy: "620001",
  Salem: "636001",
  Tirunelveli: "627001",
  Tiruppur: "641601",
  Vellore: "632001",
  Erode: "638001",
  Thoothukudi: "628001",
  Tuticorin: "628001",
  Dindigul: "624001",
  Thanjavur: "613001",
  Karur: "639001",
  Udhagamandalam: "643001",
  Ooty: "643001",
  Hosur: "635109",
  Nagercoil: "629001",
  Kanchipuram: "631501",
  Kumbakonam: "612001",
  Tiruvannamalai: "606601",
  Rameswaram: "623526",
  Kanyakumari: "629702",
  // Telangana
  Hyderabad: "500001",
  Warangal: "506002",
  Nizamabad: "503001",
  Khammam: "507001",
  Karimnagar: "505001",
  Mahabubnagar: "509001",
  Nalgonda: "508001",
  Adilabad: "504001",
  Secunderabad: "500003",
  // Tripura
  Agartala: "799001",
  // Uttar Pradesh
  Lucknow: "226001",
  Kanpur: "208001",
  Ghaziabad: "201001",
  Agra: "282001",
  Varanasi: "221001",
  Meerut: "250001",
  Prayagraj: "211001",
  Allahabad: "211001",
  Bareilly: "243001",
  Aligarh: "202001",
  Moradabad: "244001",
  Saharanpur: "247001",
  Gorakhpur: "273001",
  Noida: "201301",
  "Greater Noida": "201310",
  Firozabad: "283203",
  Jhansi: "284001",
  Muzaffarnagar: "251001",
  Mathura: "281001",
  Vrindavan: "281121",
  Ayodhya: "224123",
  Rampur: "244901",
  Shahjahanpur: "242001",
  Mirzapur: "231001",
  // Uttarakhand
  Dehradun: "248001",
  Haridwar: "249401",
  Roorkee: "247667",
  Haldwani: "263139",
  Rudrapur: "263153",
  Kashipur: "244713",
  Rishikesh: "249201",
  Nainital: "263002",
  Mussoorie: "248179",
  Almora: "263601",
  // West Bengal
  Kolkata: "700001",
  Howrah: "711101",
  Asansol: "713301",
  Siliguri: "734001",
  Durgapur: "713201",
  Bardhaman: "713101",
  Malda: "732101",
  Kharagpur: "721301",
  Haldia: "721607",
  Darjeeling: "734101",
  "Cooch Behar": "736101",
  // UTs
  "Port Blair": "744101",
  Chandigarh: "160001",
  Silvassa: "396230",
  Daman: "396210",
  Diu: "362520",
  Delhi: "110001",
  "New Delhi": "110001",
  Srinagar: "190001",
  Jammu: "180001",
  Leh: "194101",
  Kavaratti: "682555",
  Puducherry: "605001",
  Pondicherry: "605001",
  Karaikal: "609602",
};

// Case-insensitive pincode index (mirrors LOWER_INDEX above).
const PINCODE_LOWER_INDEX: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [city, pin] of Object.entries(CITY_PINCODE_MAP)) {
    out[city.toLowerCase()] = pin;
  }
  return out;
})();

/**
 * Look up the default pincode for a given city. Case-insensitive; returns
 * `null` if we don't have a curated default for that city — in which case
 * the caller should leave the pincode field empty for the user to fill.
 */
export function lookupPincodeForCity(city: string): string | null {
  if (!city) return null;
  return PINCODE_LOWER_INDEX[city.trim().toLowerCase()] ?? null;
}
